services:
  core:
    build: ./core
    ports:
      - "8000:8000"
    volumes:
      - core-data:/app
    networks:
      - monitor-net
    restart: unless-stopped

  agent:
    build: ./agent
   
    profiles:
      - donotstart
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
     
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - monitor-net
    restart: unless-stopped
    depends_on:
      - core

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitor-net
    restart: unless-stopped
    depends_on:
      - prometheus

networks:
  monitor-net:
    driver: bridge

volumes:
  core-data:
  prometheus-data:
  grafana-data: